#! /bin/sh
#
### BEGIN INIT INFO
# Provides:          pitracker
# Required-Start:    $all
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Track pi.
# Description:       This service is used to track a pi.
### END INIT INFO
case "$1" in 

 start)

  echo "starting pitracker"
   cd /home/pi/barcode_reader/bracode_reader_client
   ./barcode listener

  ;;

 stop)

  echo "stopping"  
  killall barcode



;;

esac

exit 0
